apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tor-privoxy-alpine-chart.fullname" . }}-configmap
data:
{{- range $k, $v := .Values.environmentVariables }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
